fix: 修复gradlew脚本语法错误
- 重新下载标准的gradlew脚本
- 修复GitHub Actions构建中的语法错误
- 确保POSIX shell兼容性

diff --git a/android/gradlew b/android/gradlew
--- a/android/gradlew
+++ b/android/gradlew
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 #
-# Copyright © 2010-2024 the original author or authors.
+# Copyright © 2015-2021 the original authors.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -22,36 +22,43 @@
 #
 #   Important for running:
 #
-#       (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
-#           noncompliant, but you have some other compliant shell such as ksh or
-#           bash, then to run this script, type that shell name before the whole
-#           command line, like:
+#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
+#       noncompliant, but you have some other compliant shell such as ksh or
+#       bash, then to run this script, type that shell name before the whole
+#       command line, like:
 #
-#               ksh Gradle
+#           ksh Gradle
 #
-#           Busybox and similar reduced shells will NOT work, because this script
-#           requires all of these POSIX shell features:
-#             * functions;
-#             * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
-#               «${var#prefix}», «${var%suffix}», and «$( cmd )»;
-#             * compound commands having a testable exit status, especially «case»;
-#             * various built-in commands including «command», «set», and «ulimit».
+#       Busybox and similar reduced shells will NOT work, because this script
+#       requires all of these POSIX shell features:
+#         * functions;
+#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
+#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
+#         * compound commands having a testable exit status, especially «case»;
+#         * various built-in commands including «command», «set», and «ulimit».
 #
-#           Important for patching:
+#   Important for patching:
 #
-#           (2) This script targets POSIX compliant shells. For shells that have
-#               non-POSIX compatible extensions, the script may not work as
-#               intended. The script can be patched for specific shells.
+#   (2) This script targets any POSIX shell, so it avoids extensions provided
+#       by Bash, Ksh, etc; in particular arrays are avoided.
 #
-#               The following are known to have non-POSIX compatible behavior and
-#               should be avoided if the intend is to run the script unmodified:
-#                 * dash
-#                 * zsh (when in sh mode)
-#                 * ash
-#                 * yash
+#       The "traditional" practice of packing multiple parameters into a
+#       space-separated string is a well documented source of bugs and security
+#       problems, so this is (mostly) avoided, by progressively accumulating
+#       options in "$@", and eventually passing that to Java.
 #
-#           For patching these shells, you can use the following shell script:
-#               https://github.com/gradle/gradle/blob/master/platform/jvm/pruning.sh
+#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
+#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
+#       see the in-line comments for details.
+#
+#       There are tweaks for specific operating systems such as AIX, CygWin,
+#       Darwin, MinGW, and NonStop.
+#
+#   (3) This script is generated from the Groovy template
+#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       within the Gradle project.
+#
+#       You can find Gradle at https://github.com/gradle/gradle/.
 #
 ##############################################################################
 
@@ -77,8 +84,7 @@ done
 # shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
 # Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
-APP_HOME=$( cd -P -- "$( dirname -- "$0" )" && printf '%s
-' "$PWD" ) || exit
+APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
@@ -102,7 +108,7 @@ nonstop=false
 case "$( uname )" in                #(
   CYGWIN* )         cygwin=true  ;; #(
   Darwin* )         darwin=true  ;; #(
-  MSYS* | MINGW* )  msys=true  ;; #(
+  MSYS* | MINGW* )  msys=true    ;; #(
   NONSTOP* )        nonstop=true ;;
 esac
 
@@ -180,187 +186,64 @@ if "$cygwin" || "$msys" ; then
         then
             arg=$( cygpath --path --ignore --mixed "$arg" )
         fi
-        # Roll the args around into the expected order
+        # Roll the args list around exactly as many times as the number of
+        # args, so each arg winds up back in the position where it started, but
+        # possibly modified.
+        #
+        # NB: a `for` loop captures its iteration list before it begins, so
+        # changing the positional parameters here affects neither the number of
+        # iterations, nor the values presented in `arg`.
         shift                   # remove old arg
-        set -- "$@" "$arg"     # push replacement arg
+        set -- "$@" "$arg"      # push replacement arg
     done
 fi
 
 
 # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"
+DEFAULT_JVM_OPTS='-Dfile.encoding=UTF-8 "-Xmx64m" "-Xms64m"'
 
 # Collect all arguments for the java command:
 #   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
 #     and any embedded shellness will be escaped.
-#   * For example: A user cannot expect ${HOME} to be expanded, as it is an environment variable and will be treated as
-#     ${HOME} (i.e., as an environment variable within the shell), not the Bash expansion $HOME.
-#   * For example: A user cannot expect echo "${HOME}" to be escaped as ${HOME}. Instead, it will be escaped as \${HOME}
-#     to retain the literal text ${HOME}, and then the shell will expand the ${HOME} environment variable if present.
-#     However, this does not happen on Windows because there is no shell that expands ${HOME}, so the argument is kept as is.
-#   * Any variable expansion in the command line will be performed by the shell, so if there is a variable that needs to be
-#     expanded by the Java program, it must be escaped as \\${HOME}
-#   * The only way to pass arguments that contain shell metacharacters is to escape them, either with single quotes
-#   or with backslashes. For example: a user cannot pass ${HOME} as an argument, because it will be expanded by the shell.
-#     Instead, they can pass '${HOME}' or "\${HOME}", but not '${HOME}' or "${HOME}".
-#     For Windows, the shell is different, and the expansion behavior is also different. For example, %USERPROFILE% is expanded
-#     by the shell, but ${HOME} is not. So a user can pass ${HOME} as an argument, and it will be kept as ${HOME}.
-# * For Cygwin and MSYS, the path conversion is performed, and the shell metacharacters are escaped.
-#     For example, a user can pass ${HOME} as an argument, and it will be escaped as \${HOME} and converted to %USERPROFILE% by the shell.
-# * For non-Cygwin/MSYS Windows, the shell metacharacters are escaped, but the path conversion is not performed.
-#     For example, a user can pass ${HOME} as an argument, and it will be escaped as \${HOME}, but the shell will not expand it.
+#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
+#     treated as '${Hostname}' itself on the command line.
 
-APP_NAME="Gradle"
-APP_BASE_NAME=$0
-
-# Use the maximum available, or set MAX_FD != -1 to use that value.
-MAX_FD=maximum
-
-
-# Add constants for tools that are not available on all operating systems.
-if [ "$darwin" = "true" ] ; then
-    # Darwin doesn't support GNU readlink, so use greadlink if available
-    if command -v greadlink >/dev/null 2>&1 ; then
-        READLINK=greadlink
-    else
-        READLINK=readlink
-    fi
-else
-    READLINK=readlink
-fi
-
-warn () {
-    echo "$*"
-} >&2
-
-die () {
-    echo
-    echo "$*"
-    echo
-    exit 1
-} >&2
-
-# Define a few common escape sequences for escaping shell metacharacters.
-ESCAPE_SEQUENCE_SINGLE_QUOTE='\''
-ESCAPE_SEQUENCE_DOUBLE_QUOTE='\"'
-ESCAPE_SEQUENCE_BACKSLASH='\\'
-ESCAPE_SEQUENCE_NEWLINE='$\n'
-ESCAPE_SEQUENCE_CARRIAGE_RETURN='$\r'
-ESCAPE_SEQUENCE_TAB='$\t'
-ESCAPE_SEQUENCE_DOLLAR_SIGN='$\$'
-ESCAPE_SEQUENCE_BACKTICK='\`'
-
-# Escape shell metacharacters in the argument.
-escape_shell_argument () {
-    local argument=$1
-    local result=""
-    local char=
-    local i=0
-    local length=${#argument}
-
-    for ((i=0; i<length; i++)) ; do
-        char=${argument:i:1}
-        case $char in
-            $ESCAPE_SEQUENCE_SINGLE_QUOTE)
-                result="$result$ESCAPE_SEQUENCE_BACKSLASH$ESCAPE_SEQUENCE_SINGLE_QUOTE"
-                ;;
-            $ESCAPE_SEQUENCE_DOUBLE_QUOTE)
-                result="$result$ESCAPE_SEQUENCE_BACKSLASH$ESCAPE_SEQUENCE_DOUBLE_QUOTE"
-                ;;
-            $ESCAPE_SEQUENCE_BACKSLASH)
-                result="$result$ESCAPE_SEQUENCE_BACKSLASH$ESCAPE_SEQUENCE_BACKSLASH"
-                ;;
-            $ESCAPE_SEQUENCE_NEWLINE)
-                result="$result$ESCAPE_SEQUENCE_BACKSLASH$ESCAPE_SEQUENCE_NEWLINE"
-                ;;
-            $ESCAPE_SEQUENCE_CARRIAGE_RETURN)
-                result="$result$ESCAPE_SEQUENCE_BACKSLASH$ESCAPE_SEQUENCE_CARRIAGE_RETURN"
-                ;;
-            $ESCAPE_SEQUENCE_TAB)
-                result="$result$ESCAPE_SEQUENCE_BACKSLASH$ESCAPE_SEQUENCE_TAB"
-                ;;
-            $ESCAPE_SEQUENCE_DOLLAR_SIGN)
-                result="$result$ESCAPE_SEQUENCE_BACKSLASH$ESCAPE_SEQUENCE_DOLLAR_SIGN"
-                ;;
-            $ESCAPE_SEQUENCE_BACKTICK)
-                result="$result$ESCAPE_SEQUENCE_BACKSLASH$ESCAPE_SEQUENCE_BACKTICK"
-                ;;
-            *)
-                result="$result$char"
-                ;;
-        esac
-    done
-
-    echo "$result"
-}
-
-# Escape arguments for use inside the double quotes that will be used to form the Java command line.
-escape_arguments () {
-    local result=""
-    for arg in "$@" ; do
-        local escaped_arg
-        escaped_arg=$(escape_shell_argument "$arg")
-        result="$result \"$escaped_arg\""
-    done
-    echo "$result"
-}
-
-# Escape arguments for use inside the backticks that will be used to form the eval string for the Java command line.
-escape_arguments_backticks () {
-    local result=""
-    for arg in "$@" ; do
-        local escaped_arg
-        escaped_arg=$(escape_shell_argument "$arg")
-        result="$result '$escaped_arg'"
-    done
-    echo "$result"
-}
-
-# Escape all the metacharacters in the specified argument, and then prepend the specified escape sequence.
-escape_and_prepend () {
-    local argument=$1
-    local escape_sequence=$2
-    local escaped_argument
-    escaped_argument=$(escape_shell_argument "$argument")
-    echo "$escape_sequence$escaped_argument"
-}
-
-# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"
-
-# Collect all arguments for the java command
 set -- \
         "-Dorg.gradle.appname=$APP_BASE_NAME" \
         -classpath "$CLASSPATH" \
         org.gradle.wrapper.GradleWrapperMain \
         "$@"
 
-# Stop when no more arguments should be processed (no more $*)
-# Stop when no more expansion should be done (no more ${var})
-# Stop when no more command substitution should be done (no more $(cmd))
-# Stop when no more arithmetic expansion should be done (no more $((expr)))
-# Stop when no more tilde expansion should be done (no more ~user)
-# Stop when no more parameter expansion should be done (no more ${param:-word})
-# Stop when no more pattern substitution should be done (no more ${param%pattern})
-# Stop when no more command grouping should be done (no more { cmd1; cmd2; })
-# Stop when no more subshell execution should be done (no more $(cmd))
-# Stop when no more pipe creation should be done (no more | cmd)
-# Stop when no more background process execution should be done (no more cmd &)
-# Stop when no more logical AND should be done (no more && cmd)
-# Stop when no more logical OR should be done (no more || cmd)
-# Stop when no more logical NOT should be done (no more ! cmd)
-# Stop when no more conditional execution should be done (no more if/then/else/fi)
-# Stop when no more case execution should be done (no more case/esac)
-# Stop when no more for execution should be done (no more for/do/done)
-# Stop when no more while execution should be done (no more while/do/done)
-# Stop when no more until execution should be done (no more until/do/done)
-# Stop when no more function execution should be done (no more function())
-# Stop when no more alias expansion should be done (no more alias)
-# Stop when no more glob expansion should be done (no more *)
-# Stop when no more brace expansion should be done (no more {a,b,c})
-# Stop when no more arithmetic expansion should be done (no more $((expr)))
-# Stop when no more command substitution should be done (no more $(cmd))
-# Stop when no more process substitution should be done (no more <(cmd))
-# Stop when no more pipeline should be done (no more | cmd)
+# Stop when "xargs" is not available.
+if ! command -v xargs >/dev/null 2>&1
+then
+    die "xargs is not available"
+fi
+
+# Use "xargs" to parse quoted args.
+#
+# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
+#
+# In Bash we could simply go:
+#
+#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
+#   set -- "${ARGS[@]}" "$@"
+#
+# but POSIX shell has neither arrays nor command substitution, so instead we
+# post-process each arg (as a line of input to sed) to backslash-escape any
+# character that might be a shell metacharacter, then use eval to reverse
+# that process (while maintaining the separation between arguments), and wrap
+# the whole thing up as a single "set" statement.
+#
+# This will of course break if any of these variables contains a newline or
+# an unmatched quote.
+#
+
+eval "set -- $(
+        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
+        xargs -n1 |
+        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
+        tr '\n' ' '
+    )" '"$@"'
 
 exec "$JAVACMD" "$@"
